<div id="hid_line1" style="font-family:'@{{ requestFormData.cartPreview.font }}'; color:@{{ requestFormData.cartColor.colorCode }}; font-size:@{{ requestFormData.cartPreview.fontSize }}; margin-top:@{{ requestFormData.cartPreview.marginTop1 }}; display: none;text-transform:@{{ requestFormData.cartPreview.textTransform }};">@{{requestFormData.cartPreview.line1}}</div>
<div id="hid_line2" style="font-family:'@{{ requestFormData.cartPreview.font }}'; color:@{{ requestFormData.cartColor.colorCode }}; font-size:@{{ requestFormData.cartPreview.fontSize }}; margin-top:@{{ requestFormData.cartPreview.marginTop2 }}; display: none;text-transform:@{{ requestFormData.cartPreview.textTransform }};">@{{requestFormData.cartPreview.line2}}</div>
<div id="hid_line3" style="font-family:'@{{ requestFormData.cartPreview.font }}'; color:@{{ requestFormData.cartColor.colorCode }}; font-size:@{{ requestFormData.cartPreview.fontSize }}; margin-top:@{{ requestFormData.cartPreview.marginTop3 }}; display: none;text-transform:@{{ requestFormData.cartPreview.textTransform }};">@{{requestFormData.cartPreview.line3}}</div>
{{--<div class="col-sm-7 col-xs-12 rgt_step no_pad clearfix" id="c_preview" ng-show="currentStep !='step-size' && currentStep !='step-confirm' " style="background-image: url('@{{requestFormData.cartPreview.imgBgUrl }}'" >--}}
<div class="col-sm-7 col-xs-12 rgt_step no_pad clearfix" id="c_preview" ng-show="currentStep !='step-size' && currentStep !='step-confirm' " ng-style="{'background-image': 'url(' + requestFormData.cartPreview.imgBgUrl + ')' }"  ng-cloak>
		<span class="rgt_step_content">
			<div class="line1" id="line1" style="font-family:'@{{ requestFormData.cartPreview.font }}'; color:@{{ requestFormData.cartColor.colorCode }}; font-size:@{{ requestFormData.cartPreview.fontSize }}; margin-top:@{{ requestFormData.cartPreview.marginTop1 }};text-transform:@{{ requestFormData.cartPreview.textTransform }};">@{{requestFormData.cartPreview.line1}}</div>
			<div class="line2" id="line2" style="font-family:'@{{ requestFormData.cartPreview.font }}'; color:@{{ requestFormData.cartColor.colorCode }}; font-size:@{{ requestFormData.cartPreview.fontSize }}; margin-top:@{{ requestFormData.cartPreview.marginTop2 }};text-transform:@{{ requestFormData.cartPreview.textTransform }};">@{{requestFormData.cartPreview.line2}}</div>
			<div class="line3" id="line3" style="font-family:'@{{ requestFormData.cartPreview.font }}'; color:@{{ requestFormData.cartColor.colorCode }}; font-size:@{{ requestFormData.cartPreview.fontSize }}; margin-top:@{{ requestFormData.cartPreview.marginTop3 }};text-transform:@{{ requestFormData.cartPreview.textTransform }};">@{{requestFormData.cartPreview.line3}}</div>
			<img id="slate_preview" ng-src="{{asset('front/images/step2a/')}}/@{{requestFormData.cartPreview.imgName}}" width="@{{requestFormData.cartPreview.imageW }}" height="@{{requestFormData.cartPreview.imageH }}" class="@{{requestFormData.cartPreview.styleId }}" >
		</span>
</div>